source "https://rubygems.org"

gem "autoprefixer-rails"
gem "jekyll-admin"
gem "html-proofer"
gem "image_optim"
gem "jekyll", '3.8.6'
gem "jekyll-archives"
gem "jekyll-assets"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-tagging"
gem "jekyll-responsive_image"
gem "jekyll-watch"
gem "jemoji"
gem "mini_magick"
gem "sass"
gem "sprockets", "~> 3.7"
gem "uglifier"
